sonar.host.url=http://localhost:9000
sonar.token=sqp_831a85da9c7a45877983373d4cf632d26983eb7b
sonar.projectKey=HumanWisdom_development_course_3cdfd2d1-dacc-41ea-b3ad-7833564d15a4
sonar.sources=HumanWisdom/projects/teenagers/
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js
sonar.javascript.node.maxspace=16039
sonar.ce.javaOpts=-Xmx4g -Xms512m
