# sonar.host.url=http://localhost:9000
# sonar.token=sqp_831a85da9c7a45877983373d4cf632d26983eb7b
# sonar.projectKey=HumanWisdom_development_course_3cdfd2d1-dacc-41ea-b3ad-7833564d15a4
# sonar.sources=Human_wisdom_admin/src
# sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts
# sonar.inclusions=**/*.ts,**/*.tsx
# sonar.javascript.node.maxspace=16087
# sonar.ce.javaOpts=-Xmx4g -Xms512m
# sonar.javascript.detectBundles=false


sonar.projectKey=HumanWisdom_development_course	
sonar.organization=humanwisdom	
sonar.exclusions=HumanWisdom/projects/assets/**/*,HumanWisdom/projects/shared/**/*,HumanWisdom/projects/teenagers/**/*,HumanWisdom/projects/adults/**/*,api/**/*,program/**/*
sonar.javascript.node.maxspace=16384
