name: Deploy-Website

on:
  push:
    branches: [dev]

jobs:
  build-website:
    runs-on: self-hosted

    steps:
      - name: Cleanup builds before checkout
        run: sudo rm -rf /home/ubuntu/actions-runner/_work/development_course/development_course/builds || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd HumanWisdom/projects/getStarted
          npm install

      - name: Ensure CSS directory exists
        run: mkdir -p HumanWisdom/projects/getStarted/assets-min/css

      - name: Run Gulp to minify CSS
        run: |
          cd HumanWisdom/projects/getStarted
          npx gulp

      - name: Compress build artifacts
        run: |
          cd HumanWisdom
          mkdir -p builds/compressed
          tar -czf builds/compressed/website.tgz projects/getStarted

      - name: Deploy locally
        run: |
          mkdir -p builds/uncompressed/${{ github.run_id }}
          tar -zxf HumanWisdom/builds/compressed/website.tgz -C builds/uncompressed/${{ github.run_id }}
          sudo rm -rf /var/www/html/getStarted/
          sudo mv builds/uncompressed/${{ github.run_id }}/projects/getStarted /var/www/html/
          sudo chown -R ubuntu:ubuntu /var/www/html/getStarted
